# This is a basic workflow to help you get started with Actions

name: Deploy changes

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout sources
        uses: actions/checkout@v2
        
      - name: Move sources to staging directory
        run: |
          cd $GITHUB_WORKSPACE
          rm -rvf $RUNNER_TEMP/staging/*
          cp -r . $RUNNER_TEMP/staging/

      - name: Cleanup sources
        run: |
          cd $RUNNER_TEMP/staging/
          rm -r .git .github
          rm README.md LICENSE .gitignore
      
      - name: Archive sources
        run: zip -r $RUNNER_TEMP/staging/deloro-www.zip $RUNNER_TEMP/staging/

      - name: Install sshpass
        run: sudo apt install -y sshpass

      - name: Copy artifact
        run: sshpass -p '$USER_PASSWORD' scp -p $SSH_PORT $RUNNER_TEMP/staging/deloro-www.zip $USER_NAME@SERVER_IP:~/
